[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5
    br3ttb/PID @ ^1.2.1
    # Add IMU libraries if needed later, e.g., adafruit/Adafruit MPU6050
